In [ ]:
import torch
import torch.nn as nn
import numpy as np

torch.manual_seed(0)

# ---------------------------------------------------------------------
# In classic image processing (Part 2), WE chose the numbers in the kernel.
# In a CNN, nn.Conv2d starts with RANDOM numbers, and gradient descent
# (backpropagation) adjusts them during training until they become useful.
# ---------------------------------------------------------------------

conv = nn.Conv2d(in_channels=1, out_channels=4, kernel_size=3, padding=1)

print("A freshly created nn.Conv2d layer already contains kernel numbers --")
print("but they start out RANDOM, not designed by anyone:\n")

# conv.weight shape: (out_channels, in_channels, kernel_h, kernel_w)
print("Weight tensor shape:", tuple(conv.weight.shape),
      " <- (4 different kernels, each 1-channel-in, 3x3)")




A freshly created nn.Conv2d layer already contains kernel numbers --
but they start out RANDOM, not designed by anyone:

Weight tensor shape: (4, 1, 3, 3)  <- (4 different kernels, each 1-channel-in, 3x3)


In [2]:
for i in range(4):
    print(f"\nKernel {i} (randomly initialized, untrained):")
    print(conv.weight[i, 0].detach().numpy().round(3))

print("\n" + "="*60)
print("Compare this random kernel 0 to our HAND-DESIGNED Sobel kernel:")
print("="*60)
sobel = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
print("Sobel (hand-designed, fixed forever):")
print(sobel)
print("\nCNN kernel 0 (random right now, but WILL CHANGE during training):")
print(conv.weight[0, 0].detach().numpy().round(3))

print("\nThe structural idea is IDENTICAL -- a 3x3 grid of numbers, applied")
print("by sliding + multiply + sum, exactly like Part 1 and Part 2.")
print("The only difference: Sobel's numbers are fixed by a human, forever.")
print("The CNN's numbers start random and get UPDATED by backpropagation")
print("every training step, gradually specializing into whatever pattern")
print("detectors actually help reduce the loss -- which might look like an")
print("edge detector, or something with no simple human name at all.")


Kernel 0 (randomly initialized, untrained):
[[-0.002  0.179 -0.274]
 [-0.245 -0.128  0.089]
 [-0.007  0.264 -0.03 ]]

Kernel 1 (randomly initialized, untrained):
[[ 0.088 -0.101 -0.066]
 [-0.318 -0.221 -0.137]
 [ 0.012  0.132  0.2  ]]

Kernel 2 (randomly initialized, untrained):
[[-0.226 -0.145  0.121]
 [ 0.277 -0.069  0.249]
 [-0.054  0.035  0.302]]

Kernel 3 (randomly initialized, untrained):
[[-0.309 -0.21  -0.084]
 [-0.13   0.288 -0.216]
 [-0.153 -0.233 -0.312]]

Compare this random kernel 0 to our HAND-DESIGNED Sobel kernel:
Sobel (hand-designed, fixed forever):
[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]

CNN kernel 0 (random right now, but WILL CHANGE during training):
[[-0.002  0.179 -0.274]
 [-0.245 -0.128  0.089]
 [-0.007  0.264 -0.03 ]]

The structural idea is IDENTICAL -- a 3x3 grid of numbers, applied
by sliding + multiply + sum, exactly like Part 1 and Part 2.
The only difference: Sobel's numbers are fixed by a human, forever.
The CNN's numbers start random and get UPDATED by b